<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Sign In/Register</title>        
    <!-- <link href="./node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href=<?php APP_PATH ?>"/public/assets/css/signin.css" rel="stylesheet">


    <!-- Bootstrap core CSS -->

    <style>
        <?php //require_once('../public/node_modules/bootstrap/dist/css/bootstrap.min.css'); ?>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem; 
        }
      }
        <?php //require_once('../public/css/signin.css'); ?>
    </style>
    <!-- Custom styles for this template -->
    <!-- <link href="./assets/css/signin.css" rel="stylesheet"> -->
  </head>
  <body class="text-center">
    <main class="form-signin">
        <?= $this->tag->form('login/signup');?>
            <h1 class="h3 mb-3 fw-normal">
            Sign Up
            </h1>

            <input type="hidden" name="action" value="register">
            <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" 
            placeholder="name@example.com" name="user_email" required>
            <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
            <input type="text" class="form-control" id="floatingName" placeholder="Full Name" name="user_name" required>
            <label for="floatingName">Name</label>
            </div>
            <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" 
            placeholder="Password" name="user_password" required>
            <label for="floatingPassword">Password</label>
            </div>

            <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="remember" value="remember-me"> Remember me
            </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
            </form>
        <!-- <button class="mt-2 w-100 btn-sm btn-primary rounded"> -->
        <a class="mt-2 w-100 btn-sm btn btn-primary rounded text-light text-decoration-none" 
        href="/login">
            Sign In
        </a>
        <!-- </button> -->
        <a href="/" class="btn btn-secondary my-2">Back To Home</a>
        <p class="mt-5 mb-3 text-muted">&copy; CEDCOSS Technologies</p>
    </main>
  </body>
</html>