<?php

echo $this->tag->linkTo(
    [
        URL_PATH.'/admin/order',
        "Orders",
        'class' => 'btn btn-primary m-3',
    ]
);

echo $this->tag->linkTo(
    [
        URL_PATH.'/admin/addProduct',
        "Add Product",
        'class' => 'btn btn-primary m-3',
    ]
);

echo $this->tag->linkTo(
    [
        URL_PATH.'/admin/listProduct',
        "View Product",
        'class' => 'btn btn-primary m-3',
    ]
);
