<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Sign In/Register</title>        
    <!-- <link href="./node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="<?php echo URL_PATH ?>/public/assets/css/signin.css" rel="stylesheet">

    <!-- Bootstrap core CSS -->

    <style>
        <?php //require_once('../public/node_modules/bootstrap/dist/css/bootstrap.min.css'); ?>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem; 
        }
      }
        <?php //require_once('../public/css/signin.css'); ?>
    </style>
    <!-- Custom styles for this template -->
    <!-- <link href="./assets/css/signin.css" rel="stylesheet"> -->
  </head>
  <body class="text-center">
    <main class="form-signin">
        <?= $this->tag->form(URL_PATH.'/login/login');?>
            <h1 class="h3 mb-3 fw-normal">Sign In</h1>
            <input type="hidden" name="action" value="signin">
            <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" 
            placeholder="name@example.com" name="user_email" required>
            <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" 
            placeholder="Password" name="user_password" required>
            <label for="floatingPassword">Password</label>
            </div>
    
            <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="remember" value="remember-me"> Remember me
            </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        </form>
        <!-- <button class="mt-2 w-100 btn-sm btn-primary rounded"> -->
        <a class="mt-2 w-100 btn-sm btn btn-primary rounded text-light text-decoration-none"
        href="<?php echo URL_PATH?>/login/register">
            Register
        </a>
        <!-- </button> -->
        <a href="<?php echo URL_PATH?>" class="btn btn-secondary my-2">Back To Home</a>
        <p class="mt-5 mb-3 text-muted">&copy; CEDCOSS Technologies</p>
    </main>
  </body>
</html>